package org.example;
import java.nio.file.*;import java.util.*;import java.lang.reflect.Field;import org.jf.dexlib2.*;
public final class FragmentReceiverTrace {
 static Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}
 public static void main(String[] args)throws Exception{
  Path p=Files.createTempFile("fragment-trace-",".dex");try{DexFileFactory.writeDexFile(p.toString(),LifecycleContainerFactoryProbe.buildContainer(args.length==0?"installed":args[0]));long d=System.nanoTime()+30_000_000_000L;CapabilityIndex i=new CapabilityIndex();i.read(p,d);ApkInventory a=new ApkInventory();a.activities.add("container.Host");CapabilityEngine e=new CapabilityEngine(i,a,d);Set<String> seen=new HashSet<>();boolean[] injected={false};System.out.println("RELEVANT "+i.relevant.stream().sorted().toList());var lm=i.resolve("Lcontainer/LifecycleFragment;->onActivityCreated(Landroid/os/Bundle;)V");System.out.println("COMPONENT_ENTRY "+i.componentEntry("container.LifecycleFragment",lm));
  e.checkpoint=()->{try{var h=e.currentHost;if(h==null)return;for(var x:h.heap.entrySet()){String s="HEAP "+x;if(seen.add(s))System.out.println(s);}if(args.length>1&&args[1].equals("inject")&&!injected[0])for(var x:h.heap.entrySet())if(x.getKey().contains("LifecycleFragment;->delegate:")){String id=x.getKey().substring(0,x.getKey().indexOf("::"));var receiver=DexFlow.V.of("object","container.LifecycleFragment",id);System.out.println("INTERVENTION actual_receiver="+receiver+" relevance="+e.relevantOnReceiver(lm,receiver,h));e.enqueue(h,lm,List.of(receiver,DexFlow.V.of("unknown","android.os.Bundle","diagnostic_actual_state")),List.of("diagnostic_actual_installed_fragment"),false);injected[0]=true;break;}for(String lane:List.of("priority","ordinary")){Object l=field(h.queue,lane);Map<?,?> m=(Map<?,?>)field(l,"methods");for(Object q:m.values())for(Object item:(Iterable<?>)q){CapabilityEngine.Job j=(CapabilityEngine.Job)item;if(j.method().getDefiningClass().contains("container")){String s="JOB "+CapabilityIndex.key(j.method())+" ARGS "+j.args()+" PATH "+j.path();if(seen.add(s))System.out.println(s);}}}}catch(Exception x){throw new RuntimeException(x);}};
  e.analyzeActivity("container.Host");System.out.println("FACTS "+e.activities);System.out.println("DIAG "+e.diagnostics);
  }finally{Files.deleteIfExists(p);}
 }
}
