package org.example;
import java.nio.file.*;import java.util.*;import org.jf.dexlib2.*;import org.jf.dexlib2.immutable.*;import org.jf.dexlib2.immutable.instruction.*;import org.jf.dexlib2.immutable.reference.*;import static org.example.ServiceConstructorArrayProbe.*;
/** Generic inherited holder field -> getter -> non-null native client wrapper. */
public final class InheritedWebViewWrapperProbe {
 static final String ACT="Lholder/Host;",BASE="Lholder/Base;",H="Lholder/Holder;",WV="Lholder/WrappedView;",DELEGATE="Lholder/Delegate;",WRAP="Lholder/ClientWrapper;",CLIENT="Landroid/webkit/WebViewClient;";
 static ImmutableDexFile build(String mode){List<ImmutableClassDef> ds=new ArrayList<>();
 var getter=method(BASE,"get",List.of(),W,1,2,List.of(get(0,1,BASE,"view",W),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false);
 ds.add(clazz(BASE,"Landroid/widget/LinearLayout;",List.of(),List.of(field(BASE,"view",W)),getter));
 var ensure=method(H,"ensure",List.of(),"V",1,2,List.of(make(0,WV),call(Opcode.INVOKE_DIRECT,WV,"<init>",List.of(),"V",0),put(0,1,BASE,"view",W),end()),false);
 var hg=method(H,"get",List.of(),W,1,2,List.of(call(Opcode.INVOKE_VIRTUAL,H,"ensure",List.of(),"V",1),call(Opcode.INVOKE_SUPER,BASE,"get",List.of(),W,1),result(0),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false);
 ds.add(clazz(H,BASE,List.of(),List.of(),method(H,"<init>",List.of(),"V",0x10001,1,List.of(end()),false),ensure,hg));
 var setter=method(WV,"setWebViewClient",List.of(CLIENT),"V",1,3,List.of(new ImmutableInstruction21t(Opcode.IF_EQZ,2,13),make(0,WRAP),call(Opcode.INVOKE_DIRECT,WRAP,"<init>",List.of(),"V",0),put(2,0,WRAP,"delegate",CLIENT),call(Opcode.INVOKE_SUPER,W,"setWebViewClient",List.of(CLIENT),"V",1,0),end(),call(Opcode.INVOKE_SUPER,W,"setWebViewClient",List.of(CLIENT),"V",1,2),end()),false);
 ds.add(clazz(WV,W,List.of(),List.of(),method(WV,"<init>",List.of(),"V",0x10001,1,List.of(end()),false),setter));
 ds.add(clazz(DELEGATE,CLIENT,List.of(),List.of(),method(DELEGATE,"onPageFinished",List.of(W,"Ljava/lang/String;"),"V",1,3,List.of(end()),false)));
 ds.add(clazz(WRAP,CLIENT,List.of(),List.of(field(WRAP,"delegate",CLIENT)),method(WRAP,"<init>",List.of(),"V",0x10001,1,List.of(end()),false),method(WRAP,"onPageFinished",List.of(W,"Ljava/lang/String;"),"V",1,4,List.of(get(0,1,WRAP,"delegate",CLIENT),call(Opcode.INVOKE_VIRTUAL,CLIENT,"onPageFinished",List.of(W,"Ljava/lang/String;"),"V",0,2,3),end()),false)));
 List<org.jf.dexlib2.iface.instruction.Instruction> code=new ArrayList<>();if(mode.equals("direct")||mode.equals("cleanup")){code.add(make(0,WV));code.add(call(Opcode.INVOKE_DIRECT,WV,"<init>",List.of(),"V",0));}else{code.add(make(0,H));code.add(call(Opcode.INVOKE_DIRECT,H,"<init>",List.of(),"V",0));code.add(call(Opcode.INVOKE_VIRTUAL,H,"get",List.of(),W,0));code.add(result(0));}if(mode.equals("cleanup"))code.add(zero(1));else{code.add(make(1,DELEGATE));code.add(call(Opcode.INVOKE_DIRECT,DELEGATE,"<init>",List.of(),"V",1));}code.add(call(Opcode.INVOKE_VIRTUAL,W,"setWebViewClient",List.of(CLIENT),"V",0,1));code.add(end());ds.add(clazz(ACT,"Landroid/app/Activity;",List.of(),List.of(),method(ACT,"onCreate",List.of("Landroid/os/Bundle;"),"V",1,4,code,false)));return new ImmutableDexFile(Opcodes.getDefault(),ds);}
 public static void main(String[]args)throws Exception{for(String mode:List.of("direct","holder","cleanup")){Path p=Files.createTempFile("holder-wrapper-",".dex");try{DexFileFactory.writeDexFile(p.toString(),build(mode));long d=System.nanoTime()+30_000_000_000L;CapabilityIndex i=new CapabilityIndex();i.read(p,d);ApkInventory a=new ApkInventory();a.activities.add("holder.Host");CapabilityEngine e=new CapabilityEngine(i,a,d);e.analyzeActivity("holder.Host");System.out.println(mode+"\t"+e.activities);System.out.println(mode+" diagnostics\t"+e.diagnostics);}finally{Files.deleteIfExists(p);}}}
}
