package org.example;
import java.nio.file.*;import java.util.*;import org.jf.dexlib2.*;import org.jf.dexlib2.iface.Method;import org.jf.dexlib2.iface.instruction.Instruction;import org.jf.dexlib2.immutable.*;import org.jf.dexlib2.immutable.instruction.*;import org.jf.dexlib2.immutable.reference.*;import static org.example.ServiceConstructorArrayProbe.*;import static org.example.DexFlow.*;
/** Literal metadata map -> boxed integer -> bounded forward switch -> actual object. */
final class IntegerSwitchFactoryFixture {
 static final String ROUTER="Lswitchfactory/Router;",INTEGER="Ljava/lang/Integer;";
 static ImmutableDexFile build(int count,boolean mutate,boolean branched){
  List<ImmutableClassDef> defs=new ArrayList<>();for(var cls:ServiceConstructorArrayProbe.build("direct",false,false).getClasses())if(Set.of(P,PRODUCT,B,C).contains(cls.getType()))defs.add(ImmutableClassDef.of(cls));
  List<Instruction> init=new ArrayList<>(List.of(make(0,MAP),call(Opcode.INVOKE_DIRECT,MAP,"<init>",List.of(),"V",0),new ImmutableInstruction21c(Opcode.SPUT_OBJECT,0,new ImmutableFieldReference(ROUTER,"ids",MAP))));
  for(int n=0;n<count;n++){String slot="Lswitchfactory/Slot"+n+";";defs.add(clazz(slot,P,List.of(),List.of(),method(slot,"<init>",List.of(),"V",0x10001,1,List.of(end()),false)));init.add(str(1,"switchfactory.Slot"+n));init.add(new ImmutableInstruction21s(Opcode.CONST_16,2,n));init.add(call(Opcode.INVOKE_STATIC,INTEGER,"valueOf",List.of("I"),INTEGER,2));init.add(result(2));init.add(call(Opcode.INVOKE_VIRTUAL,MAP,"put",List.of(OBJ,OBJ),OBJ,0,1,2));}
  if(mutate)init.add(call(Opcode.INVOKE_VIRTUAL,MAP,"clear",List.of(),"V",0));if(branched)init.add(new ImmutableInstruction21t(Opcode.IF_EQZ,1,1));init.add(end());
  List<Instruction> select=new ArrayList<>(List.of(new ImmutableInstruction21c(Opcode.SGET_OBJECT,0,new ImmutableFieldReference(ROUTER,"ids",MAP)),call(Opcode.INVOKE_VIRTUAL,MAP,"get",List.of(OBJ),OBJ,0,3),result(0),new ImmutableInstruction21c(Opcode.CHECK_CAST,0,new ImmutableTypeReference(INTEGER)),call(Opcode.INVOKE_VIRTUAL,INTEGER,"intValue",List.of(),"I",0),new ImmutableInstruction11x(Opcode.MOVE_RESULT,1)));
  int switchIndex=select.size();select.add(new ImmutableInstruction31t(Opcode.PACKED_SWITCH,1,1));select.add(zero(0));select.add(new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0));List<Integer> targets=new ArrayList<>();for(int n=0;n<count;n++){targets.add(units(select)-units(select.subList(0,switchIndex)));String slot="Lswitchfactory/Slot"+n+";";select.add(make(0,slot));select.add(call(Opcode.INVOKE_DIRECT,slot,"<init>",List.of(),"V",0));select.add(new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0));}
  int payload=units(select)-units(select.subList(0,switchIndex));select.set(switchIndex,new ImmutableInstruction31t(Opcode.PACKED_SWITCH,1,payload));List<ImmutableSwitchElement> elements=new ArrayList<>();for(int n=0;n<targets.size();n++)elements.add(new ImmutableSwitchElement(n,targets.get(n)));select.add(new ImmutablePackedSwitchPayload(elements));
  defs.add(clazz(ROUTER,OBJ,List.of(),List.of(new ImmutableField(ROUTER,"ids",MAP,9,null,Set.of(),Set.of())),method(ROUTER,"<clinit>",List.of(),"V",0x10008,3,init,false),method(ROUTER,"select",List.of("Ljava/lang/String;"),PRODUCT,9,4,select,false)));return new ImmutableDexFile(Opcodes.getDefault(),defs);
 }
 static int units(List<? extends Instruction> code){return code.stream().mapToInt(Instruction::getCodeUnits).sum();}
 static void run()throws Exception{
  Path dex=Files.createTempFile("integer-switch-factory-",".dex");try{
   DexFileFactory.writeDexFile(dex.toString(),build(200,false,false));long deadline=System.nanoTime()+30_000_000_000L;var index=new CapabilityIndex();index.read(dex,deadline);var engine=new CapabilityEngine(index,new ApkInventory(),deadline);var h=engine.new Host("switchfactory.Host");Method select=index.resolve(ROUTER+"->select(Ljava/lang/String;)"+PRODUCT);var job=new CapabilityEngine.Job(select,List.of(V.literal("java.lang.String","switchfactory.Slot0")),List.of("actual-factory"),false);
   for(int n:new int[]{0,130,199}){V value=engine.eval(expr("return","probe.Product",CapabilityIndex.key(select),List.of(V.literal("java.lang.String","switchfactory.Slot"+n))),job,h,0,new HashSet<>());if(!value.kind().equals("object")||!value.type().equals("switchfactory.Slot"+n))throw new AssertionError("Resolved metadata switch lost exact factory "+n+" => "+value+" gaps="+h.gaps);}
   if(engine.flow.refined!=3)throw new AssertionError("Known selector variants not reused/count exact: "+engine.flow.refined);
   for(int n:new int[]{0,130,199}){V selected=select(engine,job,h,n);Method attach=index.resolve(CapabilityEngine.desc(selected.type())+"->attach(Landroid/content/Context;Landroid/view/ViewGroup;)V");engine.enqueue(h,attach,List.of(selected,V.of("host","switchfactory.Host","activity:switchfactory.Host"),V.of("object","android.widget.FrameLayout","group:"+n)),List.of("actual-selected-"+n),true);}
   while(!h.queue.isEmpty()&&System.nanoTime()<deadline)engine.processJob(h);
   Set<String> kinds=new HashSet<>(),views=new HashSet<>();for(var fact:h.facts.values()){kinds.add(String.valueOf(fact.get("kind")));views.add(String.valueOf(((Map<?,?>)fact.get("webview")).get("id")));}
   if(!kinds.containsAll(Set.of("bridge","setting","callback"))||views.size()!=3)throw new AssertionError("Factory capability/object isolation lost: "+kinds+" views="+views);
   int before=engine.flow.refined;V dynamic=engine.eval(expr("return","probe.Product",CapabilityIndex.key(job.method()),List.of(UNKNOWN)),job,h,0,new HashSet<>());
   if(!dynamic.kind().equals("unknown")||engine.flow.refined!=before)throw new AssertionError("Unknown selector guessed or consumed variants");
   for(String missing:List.of("switchfactory.Absent","0")){int variants=engine.flow.refined;V value=engine.eval(expr("return","probe.Product",CapabilityIndex.key(job.method()),List.of(V.literal("java.lang.String",missing))),job,h,0,new HashSet<>());if(!value.kind().equals("unknown")||engine.flow.refined!=variants)throw new AssertionError("Absent/wrong key became case0 or consumed variants: "+missing+" "+value);}
   for(int n=1;n<=13;n++)select(engine,job,h,n);
   if(!select(engine,job,h,14).kind().equals("unknown")||engine.flow.refined!=16||index.diagnostics.stream().noneMatch(v->v.startsWith("summary_refinement_budget:")))throw new AssertionError("Shared16variant fallback changed");
   if(!select(engine,job,h,130).type().equals("switchfactory.Slot130"))throw new AssertionError("Existing specialized context lost at variant limit");
   V zero=IntegerConstants.resolve(IntegerConstants.BOX,List.of(V.literal("number","0")));
   if(!Boolean.FALSE.equals(DexFlow.condition("if-eqz",zero,V.literal("number","0")))||!IntegerConstants.resolve(IntegerConstants.UNBOX,List.of(V.literal("java.lang.String","0"))).equals(UNKNOWN)||!IntegerConstants.resolve(IntegerConstants.UNBOX,List.of(V.literal("number","0"))).equals(UNKNOWN))throw new AssertionError("Boxed zero/string/null conflated");
   for(String mutation:List.of("put","clear","remove","putAll","alias","escape")){
    var isolated=new CapabilityEngine(index,new ApkInventory(),deadline);var context=isolated.new Host("switchfactory.Host");V selected=select(isolated,job,context,130);if(!selected.type().equals("switchfactory.Slot130"))throw new AssertionError("Fresh certificate missing");
    V map=context.heap.get(CapabilityEngine.heapKey(ROUTER+"->ids:"+MAP,V.of("static","switchfactory.Router",ROUTER)));if(!context.constantMapSnapshots.contains(map.id()))throw new AssertionError("No actual map certificate");
    if(mutation.equals("alias"))isolated.applyWrite(context,"Lalias/Holder;->value:"+MAP,V.of("object","alias.Holder","holder"),map);
    else if(mutation.equals("escape"))isolated.invalidateConstantMapEscape(context,job,new Call("Lunknown/Helper;->consume("+MAP+")V",0,List.of(map),true,false,false));
    else if(mutation.equals("put"))isolated.applyWrite(context,"$map_entry",map,expr("map_entry",null,"entry",List.of(V.literal("java.lang.String","switchfactory.Slot130"),zero)));
    else isolated.applyWrite(context,"$map_mutation:"+MAP+"->"+mutation+"()V",map,UNKNOWN);
    if(context.constantMapSnapshots.contains(map.id())||!select(isolated,job,context,130).kind().equals("unknown"))throw new AssertionError("Mutation/escape did not invalidate guard evidence: "+mutation);
   }
  }finally{Files.deleteIfExists(dex);}
  for(boolean branch:new boolean[]{false,true}){
   Path unsafe=Files.createTempFile("unsafe-static-map-",".dex");try{DexFileFactory.writeDexFile(unsafe.toString(),build(200,!branch,branch));long deadline=System.nanoTime()+30_000_000_000L;var index=new CapabilityIndex();index.read(unsafe,deadline);var e=new CapabilityEngine(index,new ApkInventory(),deadline);var h=e.new Host("switchfactory.Host");Method m=index.resolve(ROUTER+"->select(Ljava/lang/String;)"+PRODUCT);var job=new CapabilityEngine.Job(m,List.of(V.literal("java.lang.String","switchfactory.Slot130")),List.of("unsafe"),false);if(!select(e,job,h,130).kind().equals("unknown")||!h.constantMapSnapshots.isEmpty()||h.gaps.stream().noneMatch(v->v.startsWith("static_map_initializer_unresolved:")))throw new AssertionError("Conditional/mutated initializer certified");}finally{Files.deleteIfExists(unsafe);}
  }
  Path oversized=Files.createTempFile("oversized-switch-",".dex");try{DexFileFactory.writeDexFile(oversized.toString(),build(1400,false,false));long deadline=System.nanoTime()+30_000_000_000L;var index=new CapabilityIndex();index.read(oversized,deadline);var flow=new DexFlow(index,deadline);Method method=index.resolve(ROUTER+"->select(Ljava/lang/String;)"+PRODUCT);var summary=flow.summary(method,v->v.kind().startsWith("return")&&v.id().equals(IntegerConstants.UNBOX)?V.literal("number","130"):v);if(flow.refined!=0||!summary.returns().get(0).kind().equals("unknown")||index.diagnostics.stream().noneMatch(v->v.startsWith("summary_switch_factory_budget:")))throw new AssertionError("4096 instruction boundary lost");}finally{Files.deleteIfExists(oversized);}
  System.out.println("IntegerSwitchFactoryFixture PASS: closed literal metadata, exact boxed selector and forward switch, three owned WebViews, mutation/alias/escape negatives and16/4096 bounds.");
 }
 static V select(CapabilityEngine engine,CapabilityEngine.Job job,CapabilityEngine.Host host,int n){return engine.eval(expr("return","probe.Product",CapabilityIndex.key(job.method()),List.of(V.literal("java.lang.String","switchfactory.Slot"+n))),job,host,0,new HashSet<>());}
 public static void main(String[]args)throws Exception{run();}
}
