package org.example;
import java.nio.file.*;
import java.util.*;
import org.jf.dexlib2.*;
import org.jf.dexlib2.iface.instruction.Instruction;
import org.jf.dexlib2.immutable.*;
import org.jf.dexlib2.immutable.instruction.*;
import org.jf.dexlib2.immutable.reference.*;
import static org.example.ServiceConstructorArrayProbe.*;

/** Generic actual installed Fragment -> captured root factory -> returned custom lifecycle component. */
public final class LifecycleContainerFactoryProbe {
 static final String ACT="Lcontainer/Host;",NODE="Lcontainer/Content;",CONTENT="Lcontainer/ContentContract;",FACTORY="Lcontainer/RootFactory;",CAPTURE="Lcontainer/CapturedFactory;",NAV="Lcontainer/Navigation;",CALLBACK="Lcontainer/ReadyCallback;",DISPATCH="Lcontainer/Dispatcher;",LIFE="Lcontainer/LifecycleFragment;",FRAG="Landroid/app/Fragment;",FM="Landroid/app/FragmentManager;",TX="Landroid/app/FragmentTransaction;",GROUP="Landroid/view/ViewGroup;",CTX="Landroid/content/Context;",VIEW="Landroid/view/View;",BUNDLE="Landroid/os/Bundle;";
 static ImmutableDexFile buildContainer(String route){
  List<ImmutableClassDef> ds=new ArrayList<>();
  ds.add(iface(CONTENT,method(CONTENT,"onCreateView",List.of(CTX,GROUP),VIEW,0x401,3,null,false))); // onReady declared separately below
  ds.set(0,new ImmutableClassDef(CONTENT,0x601,OBJ,List.of(),null,Set.of(),List.of(),List.of(method(CONTENT,"onCreateView",List.of(CTX,GROUP),VIEW,0x401,3,null,false),method(CONTENT,"onActivityCreated",List.of(BUNDLE),"V",0x401,2,null,false))));
  var viewCtor=method(NODE,"<init>",List.of(),"V",0x10001,1,List.of(end()),false);
  var create=method(NODE,"onCreateView",List.of(CTX,GROUP),VIEW,1,6,List.of(make(0,W),call(Opcode.INVOKE_DIRECT,W,"<init>",List.of(CTX),"V",0,4),put(0,3,NODE,"web",W),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false);
  var ready=method(NODE,"onActivityCreated",List.of(BUNDLE),"V",1,5,List.of(get(0,3,NODE,"web",W),call(Opcode.INVOKE_VIRTUAL,W,"getSettings",List.of(),S,0),result(1),new ImmutableInstruction11n(Opcode.CONST_4,2,1),call(Opcode.INVOKE_VIRTUAL,S,"setJavaScriptEnabled",List.of("Z"),"V",1,2),make(1,C),call(Opcode.INVOKE_DIRECT,C,"<init>",List.of(),"V",1),call(Opcode.INVOKE_VIRTUAL,W,"setWebViewClient",List.of("Landroid/webkit/WebViewClient;"),"V",0,1),make(1,B),call(Opcode.INVOKE_DIRECT,B,"<init>",List.of(),"V",1),str(2,"capturedRoot"),call(Opcode.INVOKE_VIRTUAL,W,"addJavascriptInterface",List.of(OBJ,"Ljava/lang/String;"),"V",0,1,2),end()),false);
  ds.add(clazz(NODE,OBJ,List.of(CONTENT),List.of(field(NODE,"web",W)),viewCtor,create,ready));ds.add(clazz(B,OBJ,List.of(),List.of(),method(B,"<init>",List.of(),"V",0x10001,1,List.of(end()),false),method(B,"invoke",List.of("Ljava/lang/String;"),"V",1,2,List.of(end()),true)));ds.add(clazz(C,"Landroid/webkit/WebViewClient;",List.of(),List.of(),method(C,"<init>",List.of(),"V",0x10001,1,List.of(end()),false),method(C,"onPageFinished",List.of(W,"Ljava/lang/String;"),"V",1,3,List.of(end()),false)));
  ds.add(iface(FACTORY,method(FACTORY,"create",List.of("Ljava/lang/ClassLoader;","Ljava/lang/String;"),CONTENT,0x401,3,null,false)));
  var capturedCtor=route.equals("direct-factory-call-valueparam")?method(CAPTURE,"<init>",List.of(CONTENT),"V",0x10001,2,List.of(put(1,0,CAPTURE,"capturedRoot",CONTENT),end()),false):route.equals("direct-factory-call-nodefield")?method(CAPTURE,"<init>",List.of(ACT),"V",0x10001,3,List.of(put(2,1,CAPTURE,"owner",ACT),get(0,2,ACT,"root",CONTENT),put(0,1,CAPTURE,"capturedRoot",CONTENT),end()),false):method(CAPTURE,"<init>",List.of(ACT),"V",0x10001,2,List.of(put(1,0,CAPTURE,"owner",ACT),end()),false);
  List<Instruction> selectCode=(route.equals("direct-factory-call-nodefield")||route.equals("direct-factory-call-valueparam"))?List.of(get(0,3,CAPTURE,"capturedRoot",CONTENT),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)):(route.equals("direct-factory-new")||route.equals("direct-factory-call-new"))?List.of(make(0,NODE),call(Opcode.INVOKE_DIRECT,NODE,"<init>",List.of(),"V",0),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)):(route.equals("direct-unconditional")||route.equals("direct-factory-call-unconditional"))?List.of(get(0,3,CAPTURE,"owner",ACT),get(1,0,ACT,"root",CONTENT),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,1)):null;
  var select=method(CAPTURE,"create",List.of("Ljava/lang/ClassLoader;","Ljava/lang/String;"),CONTENT,1,6,selectCode!=null?selectCode:List.of(get(0,3,CAPTURE,"owner",ACT),get(1,0,ACT,"root",CONTENT),str(2,"container.Content"),call(Opcode.INVOKE_VIRTUAL,"Ljava/lang/String;","equals",List.of(OBJ),"Z",2,5),new ImmutableInstruction11x(Opcode.MOVE_RESULT,2),new ImmutableInstruction21t(Opcode.IF_EQZ,2,3),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,1),zero(1),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,1)),false);
  // IF_EQZ is at code offset 10; its target zero instruction is three code units ahead.
  ds.add(clazz(CAPTURE,OBJ,List.of(FACTORY),List.of(field(CAPTURE,"owner",ACT),field(CAPTURE,"capturedRoot",CONTENT)),capturedCtor,select));
  var navCtor=method(NAV,"<init>",List.of(FACTORY),"V",0x10001,2,List.of(put(1,0,NAV,"factory",FACTORY),end()),false);
  var launch=method(NAV,"launch",List.of(CTX,GROUP,BUNDLE),"V",1,8,List.of(get(0,4,NAV,"factory",FACTORY),zero(1),str(2,route.equals("wrong-selector")?"container.Other":"container.Content"),call(Opcode.INVOKE_INTERFACE,FACTORY,"create",List.of("Ljava/lang/ClassLoader;","Ljava/lang/String;"),CONTENT,0,1,2),result(0),call(Opcode.INVOKE_INTERFACE,CONTENT,"onCreateView",List.of(CTX,GROUP),VIEW,0,5,6),result(1),call(Opcode.INVOKE_VIRTUAL,GROUP,"addView",List.of(VIEW),"V",6,1),call(Opcode.INVOKE_INTERFACE,CONTENT,"onActivityCreated",List.of(BUNDLE),"V",0,7),end()),false);
  ds.add(clazz(NAV,OBJ,List.of(),List.of(field(NAV,"factory",FACTORY)),navCtor,launch));ds.add(iface(CALLBACK,method(CALLBACK,"onActivityCreated",List.of("Landroid/app/Activity;",BUNDLE),"V",0x401,3,null,false)));
  var dctor=method(DISPATCH,"<init>",List.of(NAV,GROUP),"V",0x10001,3,List.of(put(1,0,DISPATCH,"nav",NAV),put(2,0,DISPATCH,"container",GROUP),end()),false);
  var callback=method(DISPATCH,"onActivityCreated",List.of("Landroid/app/Activity;",BUNDLE),"V",1,6,List.of(get(0,3,DISPATCH,"nav",NAV),get(1,3,DISPATCH,"container",GROUP),call(Opcode.INVOKE_VIRTUAL,NAV,"launch",List.of(CTX,GROUP,BUNDLE),"V",0,4,1,5),end()),false);
  ds.add(clazz(DISPATCH,OBJ,List.of(CALLBACK),List.of(field(DISPATCH,"nav",NAV),field(DISPATCH,"container",GROUP)),dctor,callback));
  var fctor=method(LIFE,"<init>",List.of(),"V",0x10001,1,List.of(end()),false);var set=method(LIFE,"setDelegate",List.of(CALLBACK),"V",1,2,List.of(put(1,0,LIFE,"delegate",CALLBACK),end()),false);
  var lifecycle=method(LIFE,"onActivityCreated",List.of(BUNDLE),"V",1,4,List.of(get(0,2,LIFE,"delegate",CALLBACK),call(Opcode.INVOKE_VIRTUAL,FRAG,"getActivity",List.of(),"Landroid/app/Activity;",2),result(1),call(Opcode.INVOKE_INTERFACE,CALLBACK,"onActivityCreated",List.of("Landroid/app/Activity;",BUNDLE),"V",0,1,3),end()),false);
  ds.add(clazz(LIFE,FRAG,List.of(),List.of(field(LIFE,"delegate",CALLBACK)),fctor,set,lifecycle));
  List<Instruction> e=new ArrayList<>(List.of(make(0,NODE),call(Opcode.INVOKE_DIRECT,NODE,"<init>",List.of(),"V",0),put(0,9,ACT,"root",CONTENT),make(0,CAPTURE),call(Opcode.INVOKE_DIRECT,CAPTURE,"<init>",List.of(ACT),"V",0,9),make(1,NAV),call(Opcode.INVOKE_DIRECT,NAV,"<init>",List.of(FACTORY),"V",1,0),make(2,"Landroid/widget/FrameLayout;"),call(Opcode.INVOKE_DIRECT,"Landroid/widget/FrameLayout;","<init>",List.of(CTX),"V",2,9),new ImmutableInstruction11n(Opcode.CONST_4,7,1),call(Opcode.INVOKE_VIRTUAL,VIEW,"setId",List.of("I"),"V",2,7),call(Opcode.INVOKE_VIRTUAL,"Landroid/app/Activity;","setContentView",List.of(VIEW),"V",9,2),make(3,DISPATCH),call(Opcode.INVOKE_DIRECT,DISPATCH,"<init>",List.of(NAV,GROUP),"V",3,1,2),make(4,LIFE),call(Opcode.INVOKE_DIRECT,LIFE,"<init>",List.of(),"V",4)));
  if(route.equals("direct-factory-call-valueparam")){e.set(4,call(Opcode.INVOKE_DIRECT,CAPTURE,"<init>",List.of(CONTENT),"V",0,5));e.add(3,get(5,9,ACT,"root",CONTENT));}
  if(route.startsWith("direct-factory-call")||route.equals("direct-factory-concrete")){addZero(e,5);e.add(str(6,"container.Content"));e.add(call(route.equals("direct-factory-concrete")?Opcode.INVOKE_VIRTUAL:Opcode.INVOKE_INTERFACE,route.equals("direct-factory-concrete")?CAPTURE:FACTORY,"create",List.of("Ljava/lang/ClassLoader;","Ljava/lang/String;"),CONTENT,0,5,6));e.add(result(0));e.add(call(Opcode.INVOKE_INTERFACE,CONTENT,"onCreateView",List.of(CTX,GROUP),VIEW,0,9,2));e.add(call(Opcode.INVOKE_INTERFACE,CONTENT,"onActivityCreated",List.of(BUNDLE),"V",0,5));}
  else if(route.equals("direct-node")){e.add(get(0,9,ACT,"root",CONTENT));addZero(e,5);e.add(call(Opcode.INVOKE_VIRTUAL,NODE,"onCreateView",List.of(CTX,GROUP),VIEW,0,9,2));e.add(call(Opcode.INVOKE_VIRTUAL,NODE,"onActivityCreated",List.of(BUNDLE),"V",0,5));}
  else if(route.startsWith("direct")){addZero(e,5);e.add(call(Opcode.INVOKE_VIRTUAL,DISPATCH,"onActivityCreated",List.of("Landroid/app/Activity;",BUNDLE),"V",3,9,5));}
  else {
   if(!route.equals("late-setter"))e.add(call(Opcode.INVOKE_VIRTUAL,LIFE,"setDelegate",List.of(CALLBACK),"V",4,3));
   if(!route.equals("uninstalled")){e.add(call(Opcode.INVOKE_VIRTUAL,"Landroid/app/Activity;","getFragmentManager",List.of(),FM,9));e.add(result(5));e.add(call(Opcode.INVOKE_VIRTUAL,FM,"beginTransaction",List.of(),TX,5));e.add(result(6));e.add(new ImmutableInstruction11n(Opcode.CONST_4,7,1));e.add(str(8,"container"));e.add(call(Opcode.INVOKE_VIRTUAL,TX,"add",List.of("I",FRAG,"Ljava/lang/String;"),TX,6,7,4,8));if(route.equals("late-setter"))e.add(call(Opcode.INVOKE_VIRTUAL,LIFE,"setDelegate",List.of(CALLBACK),"V",4,3));e.add(call(Opcode.INVOKE_VIRTUAL,TX,"commit",List.of(),"I",6));}
  }
  e.add(end());ds.add(clazz(ACT,"Landroid/app/Activity;",List.of(),List.of(field(ACT,"root",CONTENT)),method(ACT,"onCreate",List.of(BUNDLE),"V",1,11,e,false)));return new ImmutableDexFile(Opcodes.getDefault(),ds);
 }
 static void addZero(List<Instruction> code,int reg){code.add(zero(reg));}
 public static void main(String[]args)throws Exception{for(String route:List.of("direct-node","direct-factory-call","direct-factory-call-unconditional","direct-factory-call-new","direct-factory-call-nodefield","direct-factory-call-valueparam","direct-factory-concrete","direct-factory-new","direct-unconditional","direct","installed","late-setter","uninstalled","wrong-selector")){Path p=Files.createTempFile("lifecycle-container-",".dex");try{DexFileFactory.writeDexFile(p.toString(),buildContainer(route));long probeStart=System.nanoTime();long deadline=probeStart+30_000_000_000L;var idx=new CapabilityIndex();idx.read(p,deadline);var apk=new ApkInventory();apk.targetSdk=30;apk.activities.add("container.Host");var engine=new CapabilityEngine(idx,apk,deadline);engine.analyzeActivity("container.Host");System.out.println(route+"\t"+engine.activities);System.out.println(route+" diagnostics\t"+engine.diagnostics);System.out.println(route+" seconds\t"+((System.nanoTime()-probeStart)/1_000_000_000.0));System.out.println(route+" factorySummary\t"+engine.flow.summary(idx.resolve(CAPTURE+"->create(Ljava/lang/ClassLoader;Ljava/lang/String;)"+CONTENT)));}finally{Files.deleteIfExists(p);}}}
}
