package org.example;
import java.nio.file.*;import java.util.*;import org.jf.dexlib2.*;import org.jf.dexlib2.immutable.*;import org.jf.dexlib2.immutable.instruction.*;import static org.example.ServiceConstructorArrayProbe.*;
/** Public AndroidX transaction contracts with packaged SDK bodies, plus override/install negatives. */
public final class PackagedFragmentProtocolProbe {
 static final String ACT="Lpackaged/Host;",FA="Landroidx/fragment/app/FragmentActivity;",FM="Landroidx/fragment/app/FragmentManager;",TX="Landroidx/fragment/app/FragmentTransaction;",FRAG="Landroidx/fragment/app/Fragment;",F="Lpackaged/ContentFragment;",CTX="Landroid/content/Context;",VIEW="Landroid/view/View;",GROUP="Landroid/view/ViewGroup;",BUNDLE="Landroid/os/Bundle;";
 static ImmutableDexFile build(String mode){List<ImmutableClassDef> ds=new ArrayList<>();
 var create=method(F,"onCreateView",List.of("Landroid/view/LayoutInflater;",GROUP,BUNDLE),VIEW,1,9,List.of(make(0,W),call(Opcode.INVOKE_VIRTUAL,W,"getSettings",List.of(),S,0),result(1),new ImmutableInstruction11n(Opcode.CONST_4,2,1),call(Opcode.INVOKE_VIRTUAL,S,"setJavaScriptEnabled",List.of("Z"),"V",1,2),make(1,C),call(Opcode.INVOKE_DIRECT,C,"<init>",List.of(),"V",1),call(Opcode.INVOKE_VIRTUAL,W,"setWebViewClient",List.of("Landroid/webkit/WebViewClient;"),"V",0,1),make(1,B),call(Opcode.INVOKE_DIRECT,B,"<init>",List.of(),"V",1),str(2,"content"),call(Opcode.INVOKE_VIRTUAL,W,"addJavascriptInterface",List.of(OBJ,"Ljava/lang/String;"),"V",0,1,2),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false);
 ds.add(clazz(F,FRAG,List.of(),List.of(),method(F,"<init>",List.of(),"V",0x10001,1,List.of(end()),false),create));ds.add(clazz(C,"Landroid/webkit/WebViewClient;",List.of(),List.of(),method(C,"onPageFinished",List.of(W,"Ljava/lang/String;"),"V",1,3,List.of(end()),false)));ds.add(clazz(B,OBJ,List.of(),List.of(),method(B,"invoke",List.of("Ljava/lang/String;"),"V",1,2,List.of(end()),true)));
 List<org.jf.dexlib2.iface.instruction.Instruction> code=new ArrayList<>(List.of(make(0,F),call(Opcode.INVOKE_DIRECT,F,"<init>",List.of(),"V",0)));
 if(!mode.equals("allocated-only")){code.add(call(Opcode.INVOKE_VIRTUAL,FA,"getSupportFragmentManager",List.of(),FM,6));code.add(result(1));code.add(call(Opcode.INVOKE_VIRTUAL,FM,"beginTransaction",List.of(),TX,1));code.add(result(1));code.add(new ImmutableInstruction11n(Opcode.CONST_4,2,1));code.add(str(3,"content"));code.add(call(Opcode.INVOKE_VIRTUAL,TX,"replace",List.of("I",FRAG,"Ljava/lang/String;"),TX,1,2,0,3));if(mode.equals("packaged-sdk-show")){code.add(call(Opcode.INVOKE_VIRTUAL,TX,"show",List.of(FRAG),TX,1,0));code.add(result(1));}if(!mode.equals("uncommitted"))code.add(call(Opcode.INVOKE_VIRTUAL,TX,"commit",List.of(),"I",1));}code.add(end());List<org.jf.dexlib2.iface.Method> am=new ArrayList<>();am.add(method(ACT,"onCreate",List.of(BUNDLE),"V",1,8,code,false));
 if(mode.equals("application-super"))am.add(method(ACT,"getSupportFragmentManager",List.of(),FM,1,2,List.of(call(Opcode.INVOKE_SUPER,FA,"getSupportFragmentManager",List.of(),FM,1),result(0),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false));
 if(mode.equals("application-override"))am.add(method(ACT,"getSupportFragmentManager",List.of(),FM,1,2,List.of(zero(0),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false));ds.add(new ImmutableClassDef(ACT,1,FA,List.of(),null,Set.of(),List.of(),am));
 if(!mode.equals("absent-sdk-bodies")){ds.add(clazz(FA,"Landroid/app/Activity;",List.of(),List.of(),method(FA,"getSupportFragmentManager",List.of(),FM,1,2,List.of(make(0,FM),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false)));ds.add(clazz(FM,OBJ,List.of(),List.of(),method(FM,"beginTransaction",List.of(),TX,1,2,List.of(make(0,TX),new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false)));ds.add(clazz(TX,OBJ,List.of(),List.of(),method(TX,"replace",List.of("I",FRAG,"Ljava/lang/String;"),TX,1,4,List.of(new ImmutableInstruction11x(Opcode.RETURN_OBJECT,0)),false),method(TX,"commit",List.of(),"I",1,2,List.of(zero(0),new ImmutableInstruction11x(Opcode.RETURN,0)),false)));}return new ImmutableDexFile(Opcodes.getDefault(),ds);}
 public static void run()throws Exception{run(true);}
 static void run(boolean verify)throws Exception{for(String mode:List.of("absent-sdk-bodies","packaged-sdk-bodies","packaged-sdk-show","application-override","uncommitted","allocated-only","application-super")){Path p=Files.createTempFile("packaged-fragment-",".dex");try{DexFileFactory.writeDexFile(p.toString(),build(mode));long d=System.nanoTime()+30_000_000_000L;CapabilityIndex i=new CapabilityIndex();i.read(p,d);i.platformParents.put("androidx.fragment.app.FragmentActivity",List.of("android.app.Activity"));ApkInventory a=new ApkInventory();a.activities.add("packaged.Host");CapabilityEngine e=new CapabilityEngine(i,a,d);e.analyzeActivity("packaged.Host");System.out.println(mode+"\t"+e.activities);System.out.println(mode+" diagnostics\t"+e.diagnostics);if(verify&&!mode.equals("application-super")){Set<String> kinds=new HashSet<>();for(var activity:e.activities)for(Object f:(List<?>)activity.get("facts"))kinds.add(String.valueOf(((Map<?,?>)f).get("kind")));boolean positive=mode.equals("absent-sdk-bodies")||(mode.equals("packaged-sdk-bodies")||mode.equals("packaged-sdk-show"));if(positive&&!kinds.containsAll(Set.of("bridge","setting","callback")))throw new AssertionError("Installed public SDK contract lost categories: "+mode);if(!positive&&!kinds.isEmpty())throw new AssertionError("Uninstalled/override negative acquired capabilities: "+mode);}}finally{Files.deleteIfExists(p);}}}
 public static void main(String[]args)throws Exception{run(args.length>0&&args[0].equals("verify"));}
}
